import Form from '@/components/form'
import SectionHeader from '@/components/SectionHeader';
import Head from 'next/head'
import Navbar from '../components/Navbar';
import { useState } from 'react';
import StoryboardImage from '@/components/StoryboardImage';

export default function Home() {
  const [images, setImages] = useState<string[]>([]);
  const handleCallback = (childData: string[]) => {
    setImages(childData);
  }
  return (
    <>
      <Head>
        <title>Storyboard Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="main-content">
        <SectionHeader title='Vragen'/>
        <Form handleCallback={handleCallback}/>
        {images.length !== 0 &&
          <>
            <SectionHeader title='Scène beelden' description="Hieronder vind u de afbeeldingen terug die aan de hand van de antwoorden op de vragenlijst zijn gegenereerd. Deze afbeeldingen kunt u downloaden om te gebruiken voor uw storyboard."/>
            <div className="image-container">
              {images.map((image, index) => (
                <StoryboardImage src={image} num={index} key={index}/>
              ))}
            </div>
          </>
        }
      </main>
      <style jsx>{`
        .main-content {
          padding: 24px 130px;
          margin: 130px 0px;
        }
        .image-container {
          display: flex;
          margin-top: 50px;
          margin-bottom: 50px;
          flex-direction: row;
          flex-wrap: wrap;
          justify-content: flex-start;
          align-items: center;
          gap: 16px;
        }
      `}</style>
    </>
  )
}
