import Form from '@/components/form'
import SectionHeader from '@/components/SectionHeader';
import Head from 'next/head'
import Navbar from '../components/Navbar';
import { useState } from 'react';
import StoryboardImage from '@/components/StoryboardImage';

export default function Home() {
  const [images, setImages] = useState<string[]>([]);

  const handleCallback = (childData: string[]) => {
    setImages(childData);
  }
  return (
    <>
      <Head>
        <title>Storyboard Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="main-content">
        <SectionHeader title='Questions'/>
        <Form handleCallback={handleCallback}/>
        <SectionHeader title='Scene images'/>
        {images !== null} {
          images.map((image, index) => (
            <StoryboardImage src={image} num={index} key={index}/>
          ))
        }
      </main>
      <style jsx>{`
        .main-content {
          padding: 24px 130px;
          margin: 130px 0px;
        }
      `}</style>
    </>
  )
}
