import Head from 'next/head'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Storyboard Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="main-content">
        <div className="container">
          <h1 className="title">Introductie</h1>
          <p>Welkom bij onze handige nieuwe applicatie! Met deze app kunt u eenvoudig visuals genereren voor uw storyboard, gebaseerd op de informatie die u ons verstrekt via een eenvoudige vragenlijst. Vul alle vragen van de vragenlijst in en wij doen de rest voor u.
          Onze app is speciaal ontworpen voor programmeurs en makers van audiovisuele content om snel en efficiënt visuals te genereren. U hoeft geen tijd meer te verspillen aan het zoeken naar geschikte afbeeldingen en illustraties. Laat onze app het werk voor u doen, zodat u zich kunt concentreren op het vertellen van uw verhaal.
          Met onze app kunt u zich richten op wat echt belangrijk is: het vertellen van uw verhaal. Probeer onze app vandaag nog uit en ervaar hoe gemakkelijk het is om visuals te genereren voor uw storyboard!</p>
          <Link className="button" href="/form">Start</Link>
        </div>
      </main>
      <style jsx>{`
        .main-content {
          padding: 24px 130px;
          margin: 130px 0px;
        }
        .main-content p {
          font-size: 14px;
          font-family: Open Sans Regular;
          line-height: 19.07px;
        }
      `}</style>
    </>
  )
}
